### PR TITLE
Remove extra modules installed with source install.

### PR DESCRIPTION
**Pull request by vasiliykochergin**
I think this should take care of QA-709

### CODE REVIEW

**Comment by euca-qa-eqs-tester** [comment]
Can one of the admins verify this patch?

**Comment by tbeckham** [comment]
test this please

**Comment by tbeckham** [comment]
Well it didn't break package builds 👍

**Comment by tbeckham** [comment]
Thanks @vasiliykochergin

**Comment by tbeckham** [comment]
We had to revert this as it broke source installs in QA

**Pull request merged**
