### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ccassler**
I changed the order of eucalyptus cached repositories removal because I believe that 'yum clean all' restores them.  I think we want the eucalyptus repository cache to be completely empty when we run deploy.

### CODE REVIEW

**Comment by euca-qa-gui-tester** [comment]
Build triggered. sha1 is merged.

**Comment by euca-qa-gui-tester** [comment]
Build started sha1 is merged.

**Comment by euca-qa-gui-tester** [comment]
Build finished. No test results found.

**Comment by euca-qa-gui-tester** [comment]
Build triggered. sha1 is merged.

**Comment by euca-qa-gui-tester** [comment]
Build started sha1 is merged.

**Comment by euca-qa-gui-tester** [comment]
Build finished. No test results found.

**Comment by euca-qa-gui-tester** [comment]
Build started sha1 is merged.

**Comment by euca-qa-gui-tester** [comment]
Build finished. No test results found.

**Comment by tbeckham** [comment]
Thanks @ccassler

**Pull request merged**
