### PR TITLE
improve blockstoragemanager property configuration

### PR DESCRIPTION
**Pull request by mbacchi**
Add helper that will watch for this to be either the null string "" or "/dev/blockdev".

### CODE REVIEW

**Comment by tbeckham** [comment]
retest this please

**Comment by tbeckham** [comment]
retest this please

**Comment by tbeckham** [comment]
retest this please

**Comment by tbeckham** [comment]
retest this please

**Comment by tbeckham** [comment]
retest this please

**Comment by tbeckham** [comment]
retest this please

**Comment by nephomaniac** [comment]
Thanks Matt, can/should we add an attribute so the timeout is configurable? ie something like eucalyptus.service_timeout ?

**Comment by tbeckham** [comment]
@mbacchi you have my blessing to merge. @nephomaniac, do you concur?

**Pull request merged**
