### PR TITLE
use euca-WSDL2C.sh in source devel directory

### PR DESCRIPTION
**Pull request by mbacchi**
remove the old method(s) that used wget or grabbed the file from the
cookbook, emove the files directory in the cookbook where the
file was housed

### CODE REVIEW

**Comment by jbreiding** [comment]
The configure command should be changed to:
`+configure_command = "env JAVA_HOME='/usr/lib/jvm/java-1.8.0' JAVA='$JAVA_HOME/jre/bin/java'  EUCALYPTUS='#{home_directory}' ./configure '--with-axis2=/usr/share/axis2-*' --with-axis2c=/usr/lib64/axis2c --prefix=$EUCALYPTUS --with-apache2-module-dir=/usr/lib64/httpd/modules #{init_style} --with-db-home='#{db_home_path}' --with-wsdl2c-sh=#{euca_wsdl_path} 2>&1 | tee -a #{source_directory}/configure.out"
`

Also why are we defining EUCALYPTUS inline and using it instead of just passing in the path to prefix? This command is just a really long line so I looking for ways of making it a little simpler to understand at quick glance.

I think it might make more sense to move common directives to shared variables that are used with this command and make_command.

Outside of that the changes do correct the issue meant to be addressed.

**Comment by mbacchi** [comment]
test this

**Comment by mbacchi** [comment]
test this please

**Comment by mbacchi** [comment]
Merged manually as commit deba968d5055702aa7f194ce44b9862b7a054b08

**Pull request closed without merging**
