### PR TITLE
Allow bind-interface to be set for Java components

### PR DESCRIPTION
**Pull request by viglesiasce**

### CODE REVIEW

**Comment by euca-qa-gui-tester** [comment]
Build triggered. sha1 is merged.

**Comment by euca-qa-gui-tester** [comment]
Build started sha1 is merged.

**Comment by euca-qa-gui-tester** [comment]
Build finished. No test results found.

**Comment by euca-qa-gui-tester** [comment]
Build triggered. sha1 is merged.

**Comment by euca-qa-gui-tester** [comment]
Build started sha1 is merged.

**Comment by euca-qa-gui-tester** [comment]
Build finished. No test results found.

**Comment by viglesiasce** [comment]
retest this please

**Comment by viglesiasce** [comment]
test this please

**Pull request merged**
