### PR TITLE
Create empty default dns domain attr

### PR DESCRIPTION
**Pull request by nephomaniac**
Related to issue #226

### CODE REVIEW

**Comment by euca-qa-gui-tester** [comment]
Can one of the admins verify this patch?

**Comment by tbeckham** [comment]
test this please

**Comment by euca-qa-gui-tester** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/Eucalyptus%20Cookbook%20PR%20Monitor/141/
Test FAILed.

**Comment by tbeckham** [comment]
test this please

**Comment by euca-qa-gui-tester** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/Eucalyptus%20Cookbook%20PR%20Monitor/142/
Test FAILed.

**Comment by euca-qa-eqs-tester** [comment]
Testing

**Comment by tbeckham** [comment]
test this please

**Comment by euca-qa-gui-tester** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com/job/Eucalyptus%20Cookbook%20PR%20Monitor/148/
Test FAILed.

**Pull request merged**
