### PR TITLE
Unset proxy for eucadmin commands

### PR DESCRIPTION
**Pull request by viglesiasce**
Workaround for EUCA-10731

### CODE REVIEW

**Comment by viglesiasce** [comment]
This can be tested by running:

    export http_proxy=<your-proxy-url>
    bash <(curl -sL https://raw.githubusercontent.com/eucalyptus/eucalyptus-cookbook/master/faststart/cloud-in-a-box.sh) -u http://faststart-test.s3.amazonaws.com/cookbooks.tgz

**Comment by tbeckham** [comment]
@viglesiasce, the work around/fix for the issue looks good and works. I tested as suggested, set http_proxy and faststart install was successful. Question, is there a plan to stop using roboto and just use boto instead?

**Comment by viglesiasce** [comment]
@tbeckham, even better. In 4.2 they should be backed by requestbuilder as per @gholms new admin tools.

**Comment by viglesiasce** [comment]
Tested on 2 different setups behind proxies. Thanks @jb11211!

**Pull request merged**
