### PR TITLE
Include function to verify if SELinux is permissive or disabled to install Eucalyptus

### PR DESCRIPTION
**Pull request by joubertredrat**
Verify is SELinux is enforcing, if is, stop script and display information to user set your SELinux to permissive ou disabled

### CODE REVIEW

**Comment by euca-qa-gui-tester** [comment]
Can one of the admins verify this patch?

**Comment by joubertredrat** [comment]
Hey! I want gui test too :+1:

**Comment by euca-qa-gui-tester** [comment]
Can one of the admins verify this patch?

**Comment by euca-qa-eqs-tester** [comment]
Can one of the admins verify this patch?

**Comment by joubertredrat** [comment]
I think that repo owner don't need this, then, closed

**Pull request closed without merging**
