### PR TITLE
Create and/or edit eucalyptus.conf before starting cc and nc services

### PR DESCRIPTION
**Pull request by nephomaniac**

### CODE REVIEW

**Comment by nephomaniac** [comment]
Needs review.

**Comment by euca-qa-eqs-tester** [comment]
Can one of the admins verify this patch?

**Comment by tbeckham** [comment]
looks good to me. Bot test this please

**Comment by tbeckham** [comment]
The file path did not exist and the test failed.

[10.111.5.90] out:   * template[//etc/eucalyptus/eucalyptus.conf] action create[2016-07-19T21:27:55-07:00] INFO: Processing template[//etc/eucalyptus/eucalyptus.conf] action create (eucalyptus::node-controller line 27)
[10.111.5.90] out: 
[10.111.5.90] out:     * Parent directory /etc/eucalyptus does not exist.
[10.111.5.90] out:     ================================================================================
[10.111.5.90] out:     Error executing action `create` on resource 'template[//etc/eucalyptus/eucalyptus.conf]'
[10.111.5.90] out:     ================================================================================
[10.111.5.90] out:     
[10.111.5.90] out:     Chef::Exceptions::EnclosingDirectoryDoesNotExist
[10.111.5.90] out:     ------------------------------------------------
[10.111.5.90] out:     Parent directory /etc/eucalyptus does not exist.
[10.111.5.90] out:     
[10.111.5.90] out:     Resource Declaration:
[10.111.5.90] out:     ---------------------
[10.111.5.90] out:     # In /root/.chef/local-mode-cache/cache/cookbooks/eucalyptus/recipes/node-controller.rb
[10.111.5.90] out:     
[10.111.5.90] out:      27: template "#{node["eucalyptus"]["home-directory"]}/etc/eucalyptus/eucalyptus.conf" do
[10.111.5.90] out:      28:   source "eucalyptus.conf.erb"
[10.111.5.90] out:      29:   action :create
[10.111.5.90] out:      30: end
[10.111.5.90] out:      31: 
[10.111.5.90] out:     
[10.111.5.90] out:     Compiled Resource:
[10.111.5.90] out:     ------------------
[10.111.5.90] out:     # Declared in /root/.chef/local-mode-cache/cache/cookbooks/eucalyptus/recipes/node-controller.rb:27:in `from_file'
[10.111.5.90] out:     
[10.111.5.90] out:     template("//etc/eucalyptus/eucalyptus.conf") do
[10.111.5.90] out:       action [:create]
[10.111.5.90] out:       retries 0
[10.111.5.90] out:       retry_delay 2
[10.111.5.90] out:       default_guard_interpreter :default
[10.111.5.90] out:       source "eucalyptus.conf.erb"
[10.111.5.90] out:       declared_type :template
[10.111.5.90] out:       cookbook_name "eucalyptus"
[10.111.5.90] out:       recipe_name "node-controller"
[10.111.5.90] out:       atomic_update true
[10.111.5.90] out:       path "//etc/eucalyptus/eucalyptus.conf"
[10.111.5.90] out:     end
[10.111.5.90] out:     
[10.111.5.90] out: [2016-07-19T21:27:55-07:00] INFO: Running queued delayed notifications before re-raising exception
[10.111.5.90] out:

**Comment by tbeckham** [comment]
Bot retest this please

**Comment by nephomaniac** [comment]
Testing will merge and resubmit.

**Pull request closed without merging**
