### PR TITLE
Bindmerge

### PR DESCRIPTION
**Pull request by nephomaniac**
Allow auto discovery of the bind address using a new attribute bind-network. This allows for more flexibility in the device naming and network assignment for the registration machines/interfaces. 
This method should be replaced by the previously proposed system attributes refactor.

This needs to be further tested with fast start as well as changing the bind addr on a running cloud.

### CODE REVIEW

**Comment by euca-qa-eqs-tester** [comment]
Can one of the admins verify this patch?

**Comment by tbeckham** [comment]
ok to test

**Comment by tbeckham** [comment]
retest this please

**Comment by tbeckham** [comment]
retest this please

**Pull request merged**
