### PR TITLE
Added MAX_INSTANCES_PER_CC property to eucalyptus.conf 

### PR DESCRIPTION
**Pull request by vasiliykochergin**
The change would allow significantly reduce memory footprint for CC.

### CODE REVIEW

**Comment by euca-qa-eqs-tester** [comment]
Can one of the admins verify this patch?

**Comment by tbeckham** [comment]
Please test this

**Comment by tbeckham** [comment]
test this please

**Comment by tbeckham** [comment]
retest this please

**Comment by tbeckham** [comment]
Thanks @vasiliykochergin

**Pull request merged**
