### PR TITLE
Update to new admin tools

### PR DESCRIPTION
**Pull request by gholms**
This branch is essentially a work in progress for porting the cookbook to eucalyptus 4.2's new admin tools.  This involves removing VMware, rewriting shellouts, and reworking credential management in order to stop using eucarc files.  The intention is to make the entire cookbook use temporary setup credentials exclusively.

This depends on DNS delegation and a new eucalyptus > dns > domain attribute that I recently submitted to environment_builder.py.

I haven't tested this yet.  Let's use this branch for any needed collaboration/bugfixes/etc.

### CODE REVIEW

**Comment by euca-qa-gui-tester** [comment]
Build triggered. sha1 is merged.

**Comment by euca-qa-gui-tester** [comment]
Build started sha1 is merged.

**Comment by euca-qa-gui-tester** [comment]
Build finished. No test results found.

**Comment by euca-qa-gui-tester** [comment]
Build triggered. sha1 is merged.

**Comment by euca-qa-gui-tester** [comment]
Build started sha1 is merged.

**Comment by euca-qa-gui-tester** [comment]
Build finished. No test results found.

**Comment by gholms** [comment]
Hal, please retest this.

**Comment by gholms** [comment]
retest this please

**Comment by gholms** [comment]
Hal, retest this please

**Comment by gholms** [comment]
Oops.  I forgot I need to wait for packages to build, so retest this please.

**Comment by gholms** [comment]
Hal, retest this please

**Comment by gholms** [comment]
Hal, retest this please

**Comment by gholms** [comment]
Hal, retest this please

**Comment by gholms** [comment]
Hal, retest this please

**Comment by gholms** [comment]
Hal, retest this please

**Comment by tbeckham** [comment]
Thank you @gholms!

**Pull request merged**
